package com.esardo.a2ndhand

import android.content.Intent
import android.os.Bundle
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.navigation.NavController
import com.esardo.a2ndhand.databinding.FragmentProductBinding
import com.esardo.a2ndhand.model.Product

class ProductFragment : Fragment() {
    private lateinit var _binding: FragmentProductBinding
    private val binding get() = _binding!!
    private lateinit var navController: NavController

    private lateinit var product : Product

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        _binding = FragmentProductBinding.inflate(inflater, container, false)

        // Obtains object Product from the arguments
        product = requireArguments().getSerializable("objeto") as Product

        val ivPictures = binding.ivPictures
        val tvProdName = binding.tvProdName
        val tvPrice = binding.tvPrice
        val tvCategory = binding.tvCategory
        val tvDescription = binding.tvDescription

        //ivPictures
        tvProdName.text = product.Name
        tvPrice.text = product.Price.toString()
        //tvCategory
        tvDescription.text = product.Description


        binding.llSeller.setOnClickListener {
            //val action = productFragmentDirections //This class is autogenerated with safeargs plugin
               //.actionProductFragment
            navController.navigate(R.id.action_productFragment_to_profileFragment)
            //replace by:
            //navController.navigate(action)
        }
        return binding.root
    }
}